qa:
  - name: pgbadger
    pipeline: component-generic-parallel
    parameters:
      PRODUCT: pgbadger
      COMPONENT_REF: "v%!{PGBADGER_VERSION}"
      USE_OBS_REPO: true
      OBS_PROJECT: ${OBS_ROOTPRJ}:ppg:staging:%!{PG_MAJOR_VERSION}
      VERSION: ppg-%!{PG_VERSION}
      TEST_BRANCH: main
