#!/usr/bin/env python3
"""Replace QA Status cells in README.md with shields.io endpoint badges.

Called from the `aggregate` job of obs-nightly-qa.yml after the per-project
qa-badge-*.json files have been published to the orphan `badges` branch.

For every ``<badges-dir>/qa-badge-<slug>.json`` file, find the row in the
"## Development Projects" table of README.md whose first cell is ``<project_id>``
(where project_id = slug.replace("-", ":")) and replace the last cell with
a shields.io endpoint badge linked to the obs-nightly-qa workflow page:

    [![QA <pid>](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/<owner>/<repo>/badges/qa-badge-<slug>.json)](https://github.com/<owner>/<repo>/actions/workflows/obs-nightly-qa.yml)

Rows without a corresponding badge are left untouched (so release rows like
``ppg:releases:17.9`` keep their ``Not Available`` value).

Required env vars:
  GITHUB_REPOSITORY    e.g. "rjd15372/percona-obs-packaging"

Usage:
    update_qa_badges.py <badges-dir>
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
README = REPO_ROOT / "README.md"

BADGE_RE = re.compile(r"^qa-badge-(.+)\.json$")
ROW_PID_RE = re.compile(r"^\| `([^`]+)`")


def run(cmd: list[str], **kwargs) -> None:
    subprocess.run(cmd, check=True, **kwargs)


def discover_badges(badges_dir: Path) -> dict[str, str]:
    """Return {project_id: slug} for every qa-badge-*.json file in the dir."""
    result: dict[str, str] = {}
    for path in sorted(badges_dir.glob("qa-badge-*.json")):
        m = BADGE_RE.match(path.name)
        if not m:
            continue
        slug = m.group(1)
        project_id = slug.replace("-", ":")
        result[project_id] = slug
    return result


def make_badge_markdown(repository: str, project_id: str, slug: str) -> str:
    return (
        f"[![QA {project_id}]"
        f"(https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/"
        f"{repository}/badges/qa-badge-{slug}.json)]"
        f"(https://github.com/{repository}/actions/workflows/obs-nightly-qa.yml)"
    )


def replace_last_cell(line: str, new_value: str) -> str:
    """Replace the last cell of a well-formed markdown table row.

    Assumes no cell contents contain ``|`` — true for our table.
    """
    nl = "\n" if line.endswith("\n") else ""
    body = line[:-1] if nl else line
    parts = body.split("|")
    # "| a | b | c | d |" → ['', ' a ', ' b ', ' c ', ' d ', '']
    if len(parts) < 4 or parts[0] != "" or parts[-1] != "":
        return line
    parts[-2] = f" {new_value} "
    return "|".join(parts) + nl


def update_readme(badges_by_pid: dict[str, str], repository: str) -> bool:
    """Update README.md in place. Returns True if the file was modified.

    Only edits rows inside the "## Development Projects" section, and only when the
    section's table actually has a "QA Status" header column. This guards
    against clobbering the Package List cell on a stale 3-column table that
    has not yet been regenerated by ``update_version_lists.py``.
    """
    lines = README.read_text(encoding="utf-8").splitlines(keepends=True)

    section_start: int | None = None
    section_end = len(lines)
    for i, line in enumerate(lines):
        if line.lstrip().startswith("## Development Projects"):
            section_start = i
        elif section_start is not None and line.lstrip().startswith("## "):
            section_end = i
            break
    if section_start is None:
        print("README.md has no '## Development Projects' section; skipping.")
        return False

    header_idx: int | None = None
    for i in range(section_start, section_end):
        line = lines[i]
        if line.startswith("|") and "QA Status" in line:
            header_idx = i
            break
    if header_idx is None:
        print(
            "README.md '## Development Projects' table has no 'QA Status' column; "
            "skipping. Run update_version_lists.py first."
        )
        return False

    changed = False
    for i in range(header_idx + 1, section_end):
        line = lines[i]
        if not line.startswith("| `"):
            continue
        m = ROW_PID_RE.match(line)
        if not m or m.group(1) not in badges_by_pid:
            continue
        pid = m.group(1)
        badge_md = make_badge_markdown(repository, pid, badges_by_pid[pid])
        replaced = replace_last_cell(line, badge_md)
        if replaced != line:
            lines[i] = replaced
            changed = True

    if changed:
        README.write_text("".join(lines), encoding="utf-8")
    return changed


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <badges-dir>", file=sys.stderr)
        return 2
    badges_dir = Path(sys.argv[1])
    repository = os.environ.get("GITHUB_REPOSITORY", "")
    if not repository:
        print("GITHUB_REPOSITORY not set", file=sys.stderr)
        return 2

    badges_by_pid = discover_badges(badges_dir)
    if not badges_by_pid:
        print(f"No qa-badge-*.json files found in {badges_dir}")
        return 0
    print(f"Discovered badges for: {sorted(badges_by_pid)}")

    if not README.exists():
        print(f"{README} does not exist; nothing to update.")
        return 0

    run(
        ["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"],
        cwd=REPO_ROOT,
    )
    run(["git", "config", "user.name", "github-actions[bot]"], cwd=REPO_ROOT)
    run(["git", "pull", "--rebase"], cwd=REPO_ROOT)

    if not update_readme(badges_by_pid, repository):
        print("README.md QA Status cells already up to date.")
        return 0

    run(["git", "add", str(README)], cwd=REPO_ROOT)
    result = subprocess.run(["git", "diff", "--staged", "--quiet"], cwd=REPO_ROOT)
    if result.returncode == 0:
        print("No staged changes.")
        return 0
    run(
        ["git", "commit", "-m", "ci: update QA status badges [skip ci]"],
        cwd=REPO_ROOT,
    )
    run(["git", "push"], cwd=REPO_ROOT)
    print("QA badges committed and pushed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
