"""Unit tests for drift-tolerant content comparison (services + cmd_sync).

Some service outputs are functions of an external registry's state at
generation time rather than of any input under git:

* cargo_vendor's vendor.tar.* — percona/obs-packaging PR #5: pgvectorscale
  ships no Cargo.lock, so the crate graph is re-resolved on every run and the
  bytes drift between machines and dates.
* node_modules' node_modules.obscpio / node_modules.spec.inc and the
  package-lock.json generated by npm_lockfile — npm re-resolves ranges.

A branch-from content check comparing raw md5s would report those files as
"differs" and promote the package on unrelated PRs.  Such files are compared
by presence only; absence on either side is still a mismatch.
"""

import re

from percona_obs.cmd_sync import _content_mismatches
from percona_obs.services import drift_tolerant_patterns

SPEC = "percona-pgvectorscale.spec"
SRC = "percona-pgvectorscale_16-0.9.0.tar.gz"
VENDOR = "vendor.tar.gz"
LOCK = "package-lock.json"
CPIO = "node_modules.obscpio"
INC = "node_modules.spec.inc"


def _service_file(tmp_path, body):
    path = tmp_path / "obs" / "_service"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"<services>{body}</services>")
    return path


def _matches(patterns, name):
    return any(p.search(name) for p in patterns)


def _cargo(tmp_path):
    return drift_tolerant_patterns(
        _service_file(
            tmp_path,
            '<service mode="buildtime" name="cargo_vendor">'
            '<param name="compression">gz</param></service>',
        )
    )


def _npm(tmp_path, params=""):
    return drift_tolerant_patterns(
        _service_file(
            tmp_path,
            f'<service name="node_modules" mode="manual">{params}</service>',
        )
    )


# ── drift_tolerant_patterns ──────────────────────────────────────────────


def test_no_patterns_without_registry_services(tmp_path):
    path = _service_file(tmp_path, '<service mode="buildtime" name="tar" />')
    assert drift_tolerant_patterns(path) == []


def test_no_patterns_for_missing_or_broken_service_file(tmp_path):
    assert drift_tolerant_patterns(tmp_path / "missing" / "_service") == []
    broken = tmp_path / "broken" / "_service"
    broken.parent.mkdir()
    broken.write_text("<services><service name='x'")
    assert drift_tolerant_patterns(broken) == []


def test_cargo_vendor_patterns_cover_every_compression(tmp_path):
    pats = _cargo(tmp_path)
    for name in ("vendor.tar.gz", "vendor.tar.xz", "vendor.tar.zst"):
        assert _matches(pats, name)
    assert not _matches(pats, "vendor.tar")
    assert not _matches(pats, "my-vendor.tar.gz")
    assert not _matches(pats, SPEC)


def test_node_modules_default_patterns(tmp_path):
    pats = _npm(tmp_path)
    for name in (CPIO, INC, LOCK):
        assert _matches(pats, name)
    assert not _matches(pats, SPEC)
    assert not _matches(pats, "node_modules.sums")


def test_node_modules_patterns_follow_params(tmp_path):
    pats = _npm(
        tmp_path,
        '<param name="cpio">deps.obscpio</param>'
        '<param name="output">deps.inc</param>'
        '<param name="input">web-lock.json</param>',
    )
    for name in ("deps.obscpio", "deps.inc", "web-lock.json"):
        assert _matches(pats, name)
    assert not _matches(pats, CPIO)
    assert not _matches(pats, INC)


def test_both_services_combine(tmp_path):
    pats = drift_tolerant_patterns(
        _service_file(
            tmp_path,
            '<service mode="buildtime" name="cargo_vendor" />'
            '<service name="node_modules" mode="manual" />',
        )
    )
    assert _matches(pats, VENDOR)
    assert _matches(pats, CPIO)


# ── _content_mismatches ──────────────────────────────────────────────────


def test_vendor_only_drift_ignored_for_cargo_packages(tmp_path):
    local = {SPEC: "a", SRC: "b", VENDOR: "local-bytes"}
    obs = {SPEC: "a", SRC: "b", VENDOR: "obs-bytes"}
    assert _content_mismatches(local, obs, _cargo(tmp_path)) == []


def test_vendor_drift_reported_without_tolerant_patterns():
    local = {SPEC: "a", VENDOR: "local-bytes"}
    obs = {SPEC: "a", VENDOR: "obs-bytes"}
    assert _content_mismatches(local, obs, []) == [VENDOR]


def test_real_change_still_reported_alongside_vendor_drift(tmp_path):
    local = {SPEC: "changed", SRC: "b", VENDOR: "local-bytes"}
    obs = {SPEC: "a", SRC: "b", VENDOR: "obs-bytes"}
    assert _content_mismatches(local, obs, _cargo(tmp_path)) == [SPEC]


def test_vendor_missing_on_obs_is_a_mismatch(tmp_path):
    local = {SPEC: "a", VENDOR: "local-bytes"}
    obs = {SPEC: "a"}
    assert _content_mismatches(local, obs, _cargo(tmp_path)) == [VENDOR]


def test_vendor_missing_locally_is_a_mismatch(tmp_path):
    local = {SPEC: "a"}
    obs = {SPEC: "a", VENDOR: "obs-bytes"}
    assert _content_mismatches(local, obs, _cargo(tmp_path)) == [VENDOR]


def test_npm_artifact_drift_ignored_for_node_modules_packages(tmp_path):
    local = {SPEC: "a", LOCK: "l1", CPIO: "c1", INC: "i1"}
    obs = {SPEC: "a", LOCK: "l2", CPIO: "c2", INC: "i2"}
    assert _content_mismatches(local, obs, _npm(tmp_path)) == []


def test_npm_artifact_missing_on_obs_is_a_mismatch(tmp_path):
    local = {SPEC: "a", LOCK: "l1", CPIO: "c1", INC: "i1"}
    obs = {SPEC: "a", LOCK: "l2", INC: "i2"}
    assert _content_mismatches(local, obs, _npm(tmp_path)) == [CPIO]


def test_npm_drift_reported_for_packages_without_node_modules(tmp_path):
    local = {SPEC: "a", CPIO: "c1"}
    obs = {SPEC: "a", CPIO: "c2"}
    assert _content_mismatches(local, obs, _cargo(tmp_path)) == [CPIO]


def test_identical_content_has_no_mismatches():
    local = {SPEC: "a", SRC: "b"}
    obs = {SPEC: "a", SRC: "b"}
    assert _content_mismatches(local, obs, []) == []


def test_patterns_are_compiled_regexes(tmp_path):
    assert all(isinstance(p, re.Pattern) for p in _cargo(tmp_path))
