qa:
  - name: wal2json
    pipeline: component-generic-parallel
    parameters:
      PRODUCT: wal2json
      COMPONENT_REF: "%!{WAL2JSON_TAG}"
      USE_OBS_REPO: true
      OBS_PROJECT: ${OBS_ROOTPRJ}:ppg:staging:%!{PG_MAJOR_VERSION}
      VERSION: ppg-%!{PG_VERSION}
      TEST_BRANCH: main
