qa:
  - name: pgpool
    pipeline: component-generic-parallel
    parameters:
      PRODUCT: pgpool
      USE_OBS_REPO: true
      OBS_PROJECT: ${OBS_ROOTPRJ}:ppg:staging:%!{PG_MAJOR_VERSION}
      VERSION: ppg-%!{PG_VERSION}
      TEST_BRANCH: main
